apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/source/helm/values
        value: |
          prometheus:
            service:
              type: NodePort
              nodePort: 30090
          prometheus-node-exporter:
            service:
              port: 9300
          grafana:
            enabled: false
          prometheusOperator:
            admissionWebhooks:
              patch:
                podAnnotations:
                  sidecar.istio.io/inject: "false"
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: helm-kube-prometheus-stack
