apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app1-team1
  namespace: team1
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app1-team1
  metrics:
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 250
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Pods
        value: 1
        periodSeconds: 3 #15
    scaleDown:
      stabilizationWindowSeconds: 30 # 60
      policies:
      - type: Pods
        value: 1
        periodSeconds: 3 #15