apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: app1-team1
  namespace: team1
spec:
  cooldownPeriod: 30
  maxReplicaCount: 4
  minReplicaCount: 1
  pollingInterval: 30
  scaleTargetRef:
    name: app1-team1
  triggers:
  - type: prometheus
    metadata:
      metricName: max-mem-app1-team1
      query: |
        sum(
          container_memory_usage_bytes{
            container!="", 
            pod=~"^app1-team1-.*", 
            namespace="team1"
          }
        ) / 
        sum(
          kube_pod_container_resource_limits{
            resource="memory", 
            pod=~"^app1-team1-.*",
            container!=""
          }
        ) * 100.0
      serverAddress: http://prometheus-operated.monitoring.svc.cluster.local:9090
      threshold: '70'