apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/source/helm/values
        value: |
          prometheus:
            service:
              type: NodePort
              nodePort: 30090
            prometheusSpec:  
              additionalScrapeConfigs: |
              - job_name: 'argocd'
                scrape_interval: 30s
                scrape_timeout: 10s
                static_configs:
                  - targets: ['argocd-application-controller-metrics.argo-cd.svc.cluster.local:8082', 'argocd-redis-metrics.argo-cd.svc.cluster.local:9121']
              - job_name: 'alertManager'
                scrape_interval: 30s
                scrape_timeout: 10s
                static_configs:
                  - targets: ['alertmanager-operated.argo-cd.svc.cluster.local:9093']
          prometheus-node-exporter:
            service:
              port: 9300
          grafana:
            enabled: true
          prometheusOperator:
            admissionWebhooks:
              patch:
                podAnnotations:
                  sidecar.istio.io/inject: "false"
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: helm-kube-prometheus-stack
