apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-kube-prometheus-stack-crds
  namespace: argo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts.git
    path: charts/kube-prometheus-stack/crds/
    targetRevision: kube-prometheus-stack-44.2.1
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Replace=true
  destination:
    name: in-cluster
    namespace: monitoring
